### ISSUE TITLE
add to tape reporters list

### ISSUE THREAD

**Issue by roccomuso** [dhershman1/tap-junit#11]
Should be added to the official reporters' list. :+1: https://github.com/substack/tape#pretty-reporters

**Comment by dhershman1** [comment]
Hey! Thanks for the comment!

I took your advice and opened a PR on the tape repo here: https://github.com/substack/tape/pull/449

So we will see where it goes from there.

**Comment by dhershman1** [comment]
The PR has been accepted and merged. Thanks again for the suggestion!

**Comment by roccomuso** [comment]
great ;)
