### ISSUE TITLE
Add Version Option

### ISSUE THREAD

**Issue by znerd** [dhershman1/tap-junit#13]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
An option for retrieving the version. Either `-v` or `--version`, or both.

**Describe alternatives you've considered**
I don't see alternatives.

**Additional context**
Rationale: be able to:

1. verify easily that the program is installed, without having to have a TAP file,
2. determine the version of the program.

**Comment by dhershman1** [comment]
This feature has been added for #18 PR

**Comment by znerd** [comment]
Nice, PR looks good!
