### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by znerd** [dhershman1/tap-junit#14]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Would like to see a Docker container on Docker Hub, so instead of having to install Node, I can just use Docker to execute. E.g.:

```
docker run dhershman1/tap-junit
```

**Describe alternatives you've considered**
Alternative is that I build the Docker container myself. While that's possible and easy, I'd rather have a Docker container maintained by the original project.

**Additional context**
Here's a sample `Dockerfile` for it:

```
FROM node:8
RUN npm i -D tap-junit@2.1.0
WORKDIR /io
ENTRYPOINT [ "sh", "/node_modules/tap-junit/bin/tap-junit" ]
```

( Note that this assumes that there is a `--version` option. )

**Comment by dhershman1** [comment]
I have the docker file created for #18 but I will have to release the version to run the docker hub tests and then tweak it as needed from there.

**Comment by znerd** [comment]
`Dockerfile` looks good.

**Comment by dhershman1** [comment]
This build SHOULD be on docker hub

it's under `dhershman/tap-junit`

https://cloud.docker.com/repository/docker/dhershman/tap-junit/general

**Comment by dhershman1** [comment]
I am going to close this for now, if you're running into issues please feel free to re open it.

Thanks!

**Comment by znerd** [comment]
Sure. I have not switched yet. Once I do, I will provide feedback here. Thanks!
