### ISSUE TITLE
Show Error Output

### ISSUE THREAD

**Issue by znerd** [dhershman1/tap-junit#15]
**Is your feature request related to a problem? Please describe.**
Yes, I'm getting an exit code `1` from the program, but I don't know why.

**Describe the solution you'd like**
When there is a problem, then print a concise description of the problem to _stderr_. E.g.:

```
tap-junit: ERROR: No input file specified.
```

**Describe alternatives you've considered**
No easy alternatives (outside debugging).

**Additional context**
No additional info.

**Comment by dhershman1** [comment]
What were you doing when you didn't get error output back?

The primary situations are when tests fail (the output of those errors will be present in the output file, but I can easily make it broadcast to the terminal as well).

There's also if an issue happened up stream which I'm not to sure I'd have much info at that point but I can dig into that and check.

Other than that it should print the error object to the terminal, knowing where you might have run into this issue might help give me a spot to start for it!

**Comment by znerd** [comment]
This was my bad. It was unable to execute the script because it was missing the `+x` bit. False alarm, sorry.
