### ISSUE TITLE
Allow Specification of Input File Name on Command Line

### ISSUE THREAD

**Issue by znerd** [dhershman1/tap-junit#16]
**Is your feature request related to a problem? Please describe.**
Currently I need to pipe the contents of a file into `tap-junit` (inside a Docker container) instead of being able to just pass the TAP input file name to the command.

**Describe the solution you'd like**
I'd like the program to support a command line argument for specifying a single TAP input file. E.g.:

```
tap-junit -i input.tap -n output.xml
```

**Describe alternatives you've considered**
Just pipe the file contents into the `tap-junit` process.

**Additional context**
No additional info.

**Comment by dhershman1** [comment]
This feature is ready within #18 and waiting for release

the new option is `-i, --input` This will create a new internal stream and pipe it to the parser for the same functionality as if you were piping it directly.

**Comment by znerd** [comment]
Nice, sounds good. Thanks!
