### ISSUE TITLE
Influence Test Suite Name

### ISSUE THREAD

**Issue by znerd** [dhershman1/tap-junit#17]
**Is your feature request related to a problem? Please describe.**
I'm using `tap-junit` to show test results using the JUnit integration for Jenkins. However, Jenkins now shows the test results in this structure:

* (root)
  * test case 1 name
    * test case 1 name
    * test case 2 name

Notice that the whole test suite is named “test case 1 name” – which is not so great.

**Describe the solution you'd like**
I'd like to have either a default name (like `test suite`) or otherwise I'd like to have the option of specifying the test suite name somehow (even better).

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
No additional context.

**Comment by dhershman1** [comment]
I like this idea too, I will most likely look into it as well.

**Comment by dhershman1** [comment]
This feature has been added for #18 PR

The new option is `-s, --suite` (defaults to Tap-Junit) which will name the primary `<testsuites>` wrapper. I've also included several other attributes.

Example output:
```xml
<testsuites tests="4" name="Tap-Junit" failures="0" errors="0">
```

**Comment by znerd** [comment]
@dhershman1 Can you provide a same invocation? Would it be something like this:

```
echo tap.txt | tap-junit --suite "Tap-Junit"
```

…and:

```
echo tap.txt | tap-junit -s "Tap-Junit"
```

**Comment by dhershman1** [comment]
Yes exactly like that. If its not set it will default to "Tap-Junit"
