### ISSUE TITLE
add failure details

### ISSUE THREAD

**Issue by simonkotwicz** [dhershman1/tap-junit#2]
eg. 
```
<failure>
    ---
      operator: ok
      expected: true
      actual: null
      at: iteratorCallback (...)
    ...
</failure>
```

**Comment by dhershman1** [comment]
Ah, good thought.

**Comment by simonkotwicz** [comment]
just fyi, there is a similar npm module that exists already (https://www.npmjs.com/package/tap-xunit)

**Comment by dhershman1** [comment]
Correct but it didn't work for what I needed it for, and it doesn't support junit properly in certain cases.

**Comment by dhershman1** [comment]
Enhancement added in v1.2.1
