### ISSUE TITLE
Add ability to specify file extensions

### ISSUE THREAD

**Issue by JohanBjoerklund** [dhershman1/tap-junit#24]
**Is your feature request related to a problem? Please describe.**
In a somewhat complex build pipeline, where different testresult formats are used, we use a conventionbased system where file extsion describes the format of the testresult, e.g. testreport.xuni, testreport.vsts etc.

**Describe the solution you'd like**
The ability to specify file extension for the output file.

**Describe alternatives you've considered**
Tried tap-xunit, but the output is not compatible with our platform, looking at other options.

I will happily provide a pull request if this is something you think is a good solution.

**Comment by dhershman1** [comment]
I think I see what you mean, and in a previous version of tap-junit I think this was possible.

So instead of say tap.xml you'd want to specify that extension. I believe with the current setup if you specify one like say `.xuni` then it'd show up as `tap.xuni.xml`

You'd rather it just be `tap.xuni` correct?

**Comment by JohanBjoerklund** [comment]
Yes, that is correct. 
There is a workaround however, in just pipe the output manually like this:
`testscript | tap-junit > testresults/tests.junit`

**Comment by dhershman1** [comment]
Right, I will look into this.

I can probably just check the extension and if it exists then write the file to it as is without adding .xml, if it's blank then I can automatically add `.xml` to is.

**Comment by dhershman1** [comment]
Sorry for the delay! Work picked up a bit. I am going to try to fit this in with the fix for #23 once that fix is in place.

**Comment by dhershman1** [comment]
Released with v3.1.0
