### ISSUE TITLE
npm audit warning on use of minimist

### ISSUE THREAD

**Issue by juanpaco** [dhershman1/tap-junit#27]
**Describe the bug**

`npm audit` flags `minimist` with a low-risk prototype pollution security warning

**To Reproduce**
1. Install tap-junit in a project
2. Run `npm audit`

**Expected behavior**
No warnings given

**Screenshots**

![Screen Shot 2020-04-03 at 7 24 34 AM](https://user-images.githubusercontent.com/12894/78365338-342d4d00-757c-11ea-8fed-3e55e032a812.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: n/a, CLI tool

**Additional context**
None that I can think of.

**Comment by dhershman1** [comment]
v3.1.1 of tap-junit released on npm with this fix you added. Thanks again!
