### ISSUE TITLE
3.1.1 strangeness when installed with yarn instead of npm

### ISSUE THREAD

**Issue by jbergknoff-rival** [dhershman1/tap-junit#29]
**Describe the bug**

As of 3.1.1, tap-junit fails to run when installed with `yarn`.

```
$ ./node_modules/.bin/tap-junit -v
': No such file or directory
```

**To Reproduce**

It doesn't work when installed with `yarn`:

```
$ docker run -it --rm node:13.12.0-alpine3.11 sh
/ # yarn add tap-junit@3.1.1
...
Done in 1.22s.
/ # ./node_modules/.bin/tap-junit -v
': No such file or directory
```

It does work when installed with `npm`:

```
/ # npm install tap-junit@3.1.1
...
+ tap-junit@3.1.1
added 17 packages from 12 contributors and audited 17 packages in 2.039s
found 0 vulnerabilities

/ # ./node_modules/.bin/tap-junit -v
3.1.1
```

It worked with `yarn` in 3.1.0:

```
/ # yarn add tap-junit@3.1.0
...
Done in 1.10s.
/ # ./node_modules/.bin/tap-junit -v
3.1.0
```

**Expected behavior**
I expected tap-junit to run (in the case above, a version string should be printed).

**Desktop (please complete the following information):**
I'm running Ubuntu 18.04, though the instructions using Docker, above, should be universally reproducible.

**Comment by dhershman1** [comment]
Sorry if this was your first go to, but did you try removing your yarn lock file? I don't use yarn and I don't have my machine in front of me to test it right now. Though I will look into the weirdness that is happening because they only thing that changed was a version bump to minimist.

**Comment by jbergknoff-rival** [comment]
Yeah, these repro instructions put you in a completely blank slate with no yarn.lock.

**Comment by dhershman1** [comment]
I assumed so, I can reproduce it exactly as you portrayed, but it's hard to test fixes, I think this may be at the core a minimist problem, I'm going to attempt to switch minimist out with meow and see if that helps after I package it.

After testing to make sure if I use npm pack it still breaks of course.

**Comment by dhershman1** [comment]
Update: So of course when I install it from the tar file created by npm pack it works just fine...

**Comment by dhershman1** [comment]
I released version 3.1.2 onto npm, I ran a yarn add and it seems to be working again, do you mind trying version 3.1.2 and seeing if this fixes your issue?

**Comment by jbergknoff-rival** [comment]
Yep! 3.1.2 seems to fix it. Thanks!

**Comment by dhershman1** [comment]
Awesome! thanks!
