### ISSUE TITLE
failure does not fulfil the junit xml schema

### ISSUE THREAD

**Issue by jscriptcoder** [dhershman1/tap-junit#6]
Hi there,

I realised that the output when there is a failure does not follow the junit xml scheme:
```xml
<testcase>
  <failure type="type" message="message"></failure>
  <system-out>stdout text</system-out>
  <system-err>stderr text</system-err>
</testcase>
```
Instead, tap-junit is outputing
```xml
<testcase>
  <failure>
    <system-out>stdout text</system-out>
  </failure>
</testcase>
```
This is causing some plugins, such as Jenkins junit don't understand this xml.

JUnit xml schema: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd
Example file: http://llg.cubic.org/docs/junit/

Thanks,
Fran

**Comment by dhershman1** [comment]
Hmm, I didn't notice it wasn't outputting a type or message or even a `system-err` thanks for the catch I will dig into it shortly. 

Nice find!

**Comment by jscriptcoder** [comment]
Hi @dhershman1, first of all, thanks for the quick reply. I can make a pull request if you want. I got a potential solution.

Let me know.

**Comment by dhershman1** [comment]
Sure thing go ahead!

**Comment by dhershman1** [comment]
PR #7 should address issue thanks for the help!
